### ISSUE TITLE
Print string UTF-8

### ISSUE THREAD

**Issue by vietlv** [looped-labs/ESCPOSPrintServiceDemo#1]
Hello,
I use your app but print error font utf-8.
Help me?

**Comment by ntha314159** [comment]
Hi,
Do you know if your printer supports UTF-8 ? 
Can you please give more info on whats the error you are facing.

**Comment by vietlv** [comment]
My printer has supports but ESCPOSPrintServiceDemo app supports Ascii , Hex.

**Comment by ntha314159** [comment]
It is just a byte array that we pass so it should not be a problem. 

I will be able to help you only if you can give details of the error that you are facing.

**Comment by vietlv** [comment]
I print text "việt nam" or print hex "7669E1BB8774206E616D" but error font.
ESCPOSPrintServiceDemo only support Ascii ?

**Comment by ntha314159** [comment]
The Print Service is Language neutral. it just passes an byte array, it does not know if the data is ASCII or HEX or UTF-8 or anything else... 

if your printer supports the text it should print fine.

Also please ensure that any command that you are passing to the printer is understood by the printer.

**Comment by vietlv** [comment]
Ok thanks you,
I was checked infomation my pinter, it not support UTF-8

**Comment by vietlv** [comment]
Now, i want print Bitmap image, help me code?
